MichaelStahr/CalorieCounter

- CalorieCounter/CalorieCounter.Android/Resources/Resource.designer.cs
- CalorieCounter/CalorieCounter.UWP/App.xaml.cs
- CalorieCounter/CalorieCounter.UWP/MainPage.xaml.cs
- CalorieCounter/CalorieCounter.iOS/AppDelegate.cs
- CalorieCounter/CalorieCounter/App.xaml.cs
- CalorieCounter/CalorieCounter/CalorieCounter.csproj
- CalorieCounter/CalorieCounter/ChartData.cs
- CalorieCounter/CalorieCounter/ExtraDetailsPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/Page1.xaml
- CalorieCounter/CalorieCounter/Page3.xaml
- CalorieCounter/CalorieCounter/Page3.xaml.cs
> Graph feature

- CalorieCounter/CalorieCounter.Android/CalorieCounter.Android.csproj
- CalorieCounter/CalorieCounter.UWP/CalorieCounter.UWP.csproj
- CalorieCounter/CalorieCounter.iOS/CalorieCounter.iOS.csproj
- CalorieCounter/CalorieCounter/CalorieCounter.csproj
- CalorieCounter/CalorieCounter/FoodItem.cs
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
- CalorieCounter/CalorieCounter/RestService.cs
Add RestService class, FoodItem class
Added functionality for connecting to our db through the API
Added functionality for connecting to Miami API
> Data Display

- CalorieCounter/CalorieCounter/FoodEaten.cs
- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
- CalorieCounter/CalorieCounter/RestService.cs
- CalorieCounter/CalorieCounter/UserLogData.cs
Functionality for user adding food on UI and adding food to DB
> Add food feature

- CalorieCounter/CalorieCounter/ExtraDetailsPage.xaml
- CalorieCounter/CalorieCounter/ExtraDetailsPage.xaml.cs
- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
- CalorieCounter/CalorieCounter/RestService.cs
Displays foods for selected calendar data on extra details page
> Added functionality for displaying foods on extra details page

- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/Page2.xaml.cs
- CalorieCounter/CalorieCounter/RestService.cs
Added feature to grab miami food items and insert into our DB
> Xml insert

- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
Small change to Page 2
- Removed unnecessary other tabs for Miami and uptown since we are just doing miami food
- List of foods is better formatted
> Updated frames on page2

- CalorieCounter/CalorieCounter/DailyValues.cs
- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/RestService.cs
Updated DailyValues class to reflect the offered db table
Added new functionality for displaying daily values of a user on the home page
-  Same worked on the DB side of things
> Updated Homepage

- CalorieCounter/CalorieCounter/ChartData.cs
- CalorieCounter/CalorieCounter/ChartViewModel.cs
- CalorieCounter/CalorieCounter/ExtraDetailsPage.xaml.cs
- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/RestService.cs
- CalorieCounter/CalorieCounter/SimpleFood.cs
- Functionality for chart to show real data
- Data on chart matches display on homepage
- Added new sp to show food list on home page instead of extra details page
> Data chart

- CalorieCounter/CalorieCounter/App.xaml.cs
- CalorieCounter/CalorieCounter/CalorieCounter.csproj
- CalorieCounter/CalorieCounter/SignUpPage.xaml
- CalorieCounter/CalorieCounter/SignUpPage.xaml.cs
- CalorieCounter/CalorieCounter/WelcomePage.xaml
- CalorieCounter/CalorieCounter/WelcomePage.xaml.cs
Added welcome page and sign up page
- functionality for actually logging in / signing up not present
> Added welcome and sign up page

- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
Added new functionality for searching food by name limited by location 
Removed favs and history tabs on adding food page
> Search food by name

- CalorieCounter/CalorieCounter/Page1.xaml
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/WelcomePage.xaml
Add (nonfunctional) welcome page and sign up page
> Added welcome page and sign up page

- CalorieCounter/CalorieCounter.Android/Resources/Resource.designer.cs
- CalorieCounter/CalorieCounter.UWP/App.xaml.cs
- CalorieCounter/CalorieCounter/AddItemPopUpModel.cs
- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml
- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml.cs
- CalorieCounter/CalorieCounter/AddPopUpViewModel.cs
- CalorieCounter/CalorieCounter/CalorieCounter.csproj
- CalorieCounter/CalorieCounter/ChartData.cs
- CalorieCounter/CalorieCounter/ChartViewModel.cs
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
Added pop up page for potential items the user will add
- Delete and add all button
- List of items with their count 
- Stepper to increase or decrease quantity of items
- Adjusted layout
> Page2 add count

- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
Adjusted chart Data
- Shows current week of date selected 
- Chart changes based on user switching pages or selected new date
- Added preferences to keep the current selected date the correct value
Layout changes to buttons on homepage
> Week chart data

- CalorieCounter/CalorieCounter/MainPage.xaml
> Adjusted chart color, framing, margins, and axis

- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
Changes some colors to the graph and names in xaml
> Chart UI Changes

- CalorieCounter/CalorieCounter/MainPage.xaml
Made simple food list a grid, updated colors, fixed spacing, removed scroll view
> Updated simple food list ui

- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
Search bar instead of entry 
- items and frame and add buttons only appear when search actually returns items
> Search Bar

- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
Add functionality of highlighting the current selected day on the chart
- color of bar highlighted bar matches color of date label
> Home page chart highlight

- CalorieCounter/CalorieCounter/MainPage.xaml
Created style resource for chart markers
> Chart Markers

- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml
- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml.cs
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
Add Pop up closes on save
Save button on page 2 enabled and disabled depending if items are returned
Items List stays as is on page change
> PopUp and Page2 Actions

- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
Enable/disable forward buttons when selected date is today
Changed color of bar, calendar, and graph slightly
> HomePage Functionality

- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml
- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml.cs
Delete changed to Delete All
- moved to bottom of pop up
Stepper can be made 0, item will not be added when save clicked
> Popup Page Delete Button

- CalorieCounter/CalorieCounter/DailyValues.cs
- CalorieCounter/CalorieCounter/MainPage.xaml
Fixed issues with carbs field, changed size of grid of Nutritional info
> Nutritional Info Grid

- CalorieCounter/CalorieCounter.Android/MainActivity.cs
- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml.cs
- CalorieCounter/CalorieCounter/CalorieCounter.csproj
- CalorieCounter/CalorieCounter/MainPage.xaml
- CalorieCounter/CalorieCounter/MainPage.xaml.cs
- CalorieCounter/CalorieCounter/Page2.xaml.cs
- CalorieCounter/CalorieCounter/WelcomePage.xaml.cs
Major change:
- api and db moved to server so new url put in place 
- added pop up initiation for android
> New API URL

- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml
- CalorieCounter/CalorieCounter/Page2.xaml
Adjusted page 2 items list
- Rounded the corners
- Fixed spacing of items in list
- Removed portion size, added calories
- Changed font sizes to smaller
Adjusted add items pop up list
- Changed font sizes to smaller
- to do: fix stepper
> Listview fixes

- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml
- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml.cs
- CalorieCounter/CalorieCounter/CustomStepper.cs
- CalorieCounter/CalorieCounter/WelcomePage.xaml
- CalorieCounter/CalorieCounter/WelcomePage.xaml.cs
Added Custom Stepper to fix sizing and spacing of built in xamarin stepper
Adjusted alignment of list view 
Small addition to welcome page: added welcome message with name of user
> Stepper fix on Pop up page

- CalorieCounter/CalorieCounter/AddItemsPopUp.xaml.cs
- CalorieCounter/CalorieCounter/CalorieCounter.csproj
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
> final changes

- CalorieCounter/CalorieCounter/Location.cs
- CalorieCounter/CalorieCounter/Page2.xaml
- CalorieCounter/CalorieCounter/Page2.xaml.cs
- CalorieCounter/CalorieCounter/RestService.cs
Added a rest method to get active locations (locations that are in offered table) 
Added (not open) to locations list on page 2 if that location is not open/not active/no food listed
> Locations List on Page 2 Update
